### ISSUE TITLE
Snippets are not populating

### ISSUE THREAD

**Issue by ChrisMcPherson** [JoBrad/hive-sql-vscode#1]
I was able to successfully install the extension and view an .hql file with the advertised formatting. However, I am unable to view any available snippets using ctrl + space or complete a snippet with tab while typing "CREATE".

**Comment by JoBrad** [comment]
I noticed that this wasn't working for me, as well, after a recent setup on a new PC. I'll see if I can correct this soon.

**Comment by JoBrad** [comment]
The newest release addresses this. Thanks, and sorry for the delay!
