### ISSUE TITLE
Is it possible that we use this extension along with "Better Comments"?

### ISSUE THREAD

**Issue by swordfishray** [JoBrad/hive-sql-vscode#5]
The link is here: https://github.com/aaron-bond/better-comments
I really love your extension for hive syntax highlighting! However I couldn't get this working in conjunction with better-comments... it's a shame that two great packages cannot work together.

Thanks!

**Comment by JoBrad** [comment]
I haven't had the chance to update this package, so I'm just now getting to these issues. 

Looking at the Better Comments packaging, it seems like it should work, since it supports SQL. Can you add file-extension mapping to it?
