### ISSUE TITLE
Please also include "INNER" keyword here

### ISSUE THREAD

**Issue by swordfishray** [JoBrad/hive-sql-vscode#6]
Thanks bro.

https://github.com/JoBrad/hive-sql-vscode/blob/fcfa3bdc92cbb3357edffb1d3efc83d39160b907/syntaxes/hive.tmLanguage.json#L41

**Comment by JoBrad** [comment]
Resolved with [newest release](https://github.com/JoBrad/hive-sql-vscode/tree/0.0.3)!
